### PR TITLE
Create a UI for login page [Delivers #160166953]

### PR DESCRIPTION
**Pull request by joelethan**
PR to add User Interface to the master branch

### CODE REVIEW

**Comment by Luleherll** [comment]
this is good work

**Comment by kdaglas** [comment]
Your UI looks great... have you hosted on the gh-pages... i don't see your link or any link.

**Comment by alexkayabula** [comment]
Nice UI...... WELL DONE

**Comment by alexkayabula** [comment]
Nice UI well done

**Comment by Ivankivu** [comment]
Nice stuff..keep going

**Pull request merged**
